export const LOAD_TOPICS = 'LOAD_TOPICS'
export const CREATE_TOPIC = 'CREATE_TOPIC'
export const UPDATE_TOPIC = 'UPDATE_TOPIC'
export const GET_ALL_TOPICS = 'GET_ALL_TOPICS'
export const DELETE_TOPIC = 'DELETE_TOPIC'

