export const LOAD_PROJECTS = 'LOAD_'
export const CREATE_PROJECTS = 'CREATE_PROJECTS'
export const UPDATE_PROJECTS = 'UPDATE_PROJECTS'
export const GET_ALL_PROJECTS = 'GET_ALL_PROJECTS'
export const DELETE_PROJECTS = 'DELETE_PROJECTS'

export const LOAD_ENROLLMENT = 'LOAD_ENROLLMENT'
export const ENROLL_PROJECTS = 'ENROLL_PROJECTS'
export const UN_ENROLL_PROJECTS = 'UN_ENROLL_PROJECTS'
